const styles = {
  wrapper: {
    display: 'flex',
    justifyContent: 'space-around',
    padding: '20px',
    fontFamily: 'Arial, sans-serif',
    flexWrap: 'wrap',
    gap: '20px',
  },
  formSection: {
    width: '45vw',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    background: '#f9f9f9',
    padding: '20px',
    borderRadius: '10px',
    boxShadow: '0 4px 10px rgba(0,0,0,0.08)',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'row',
    gap: '16px',
  },
  inputGroup: {
    backgroundColor: '#ffffff',
    padding: '16px',
    borderRadius: '8px',
    boxShadow: '0 0 8px rgba(0,0,0,0.05)',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    width: '48%',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  doubleFieldGroup: {
    display: 'flex',
    gap: '12px',
    justifyContent: 'space-between',
  },
  label: {
    fontWeight: '600',
    fontSize: '13px',
    color: '#333',
  },
  input: {
    padding: '8px 10px',
    borderRadius: '5px',
    border: '1px solid #ccc',
    fontSize: '14px',
    background: '#fefefe',
    width: '100%',
    maxWidth: '100%',
    boxSizing: 'border-box',
  },
  invoice: {
    width: '600px',
    padding: '20px',
    border: '2px solid #000',
    backgroundColor: '#fff',
    textAlign: 'center',
    minWidth: '350px',
    position: 'relative',
    overflow: 'hidden',
  },
  invoiceHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    textAlign: 'left',
    gap: '20px',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    marginTop: '10px',
  },
  th: {
    border: '1px solid black',
    padding: '6px',
    textAlign: 'center',
    backgroundColor: '#e0e0e0',
  },
  td: {
    borderLeft: '1px solid black',
    borderRight: '1px solid black',
    borderTop: 'none',
    borderBottom: 'none',
    padding: '6px',
    textAlign: 'center',
  },
  lastRowTd: {
    borderLeft: '1px solid black',
    borderRight: '1px solid black',
    borderBottom: '1px solid black',
    padding: '6px',
    textAlign: 'center',
  },
  summary: {
    textAlign: 'right',
    marginTop: '10px',
    lineHeight: '1.5',
  },
  itemListHead: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemList: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#f1f1f1',
    padding: '6px 10px',
    marginBottom: '4px',
    borderRadius: '4px',
  },
  actionBtn: {
    marginLeft: '5px',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    fontSize: '16px',
  },
  button: {
    marginTop: '8px',
    padding: '10px 12px',
    background: '#4CAF50',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    fontWeight: 'bold',
    fontSize: '14px',
    cursor: 'pointer',
    transition: '0.3s',
  },
  watermark: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%) rotate(-30deg)',
    fontSize: '60px',
    color: 'rgba(0, 0, 0, 0.08)',
    whiteSpace: 'nowrap',
    pointerEvents: 'none',
    zIndex: 0,
  },
};

export default styles;
